language: ubuntu:18.04
script:
  - docker-compose build
  - docker-compose up
  - zip -r lizard-docs.zip build/
# Deploy uploads the zipfile to https://artifacts.lizard.net, but
# only when building master. It then turns up on https://docs.lizard.net
deploy:
  provider: script
  skip_cleanup: true
  script: bash upload-artifact.sh
  on:
    branch: master
