name: test

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:


jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the code.
      - uses: actions/checkout@v2

      - name: build
        run: |
          docker-compose build
          docker-compose run builder make html latexpdf
          docker-compose run builder cp build/latex/lizard.pdf build/html
          zip -r lizard-docs.zip build/html

      - name: Publish master to https://docs.lizard.net
        if: github.event.ref == 'refs/heads/master'
        run: bash upload-artifact.sh
        env:
          ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}
